services:
    kafka_controller_1:
        image: bitnami/kafka:3.4
        container_name: kafka_controller_1
        networks:
            - kafka-network
        ports:
            - 29092:29092
        environment:
            KAFKA_CFG_NODE_ID: 1
            KAFKA_CFG_PROCESS_ROLES: controller
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
            KAFKA_CFG_LISTENERS: CONTROLLER://:29092
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller_1:29092,2@kafka_controller_2:29093,3@kafka_controller_3:29094
            KAFKA_KRAFT_CLUSTER_ID: OGETnS3qyk2qgAXb0EcENQ
    kafka_controller_2:
        image: bitnami/kafka:3.4
        container_name: kafka_controller_2
        networks:
            - kafka-network
        ports:
            - 29093:29093
        environment:
            KAFKA_CFG_NODE_ID: 2
            KAFKA_CFG_PROCESS_ROLES: controller
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
            KAFKA_CFG_LISTENERS: CONTROLLER://:29093
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller_1:29092,2@kafka_controller_2:29093,3@kafka_controller_3:29094
            KAFKA_KRAFT_CLUSTER_ID: OGETnS3qyk2qgAXb0EcENQ
    kafka_controller_3:
        image: bitnami/kafka:3.4
        container_name: kafka_controller_3
        networks:
            - kafka-network
        ports:
            - 29094:29094
        environment:
            KAFKA_CFG_NODE_ID: 3
            KAFKA_CFG_PROCESS_ROLES: controller
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
            KAFKA_CFG_LISTENERS: CONTROLLER://:29094
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller_1:29092,2@kafka_controller_2:29093,3@kafka_controller_3:29094
            KAFKA_KRAFT_CLUSTER_ID: OGETnS3qyk2qgAXb0EcENQ
    kafka_broker_1:
        image: bitnami/kafka:3.4
        container_name: kafka_broker_1
        ports:
            - 9092:9092
            - 9093:9093
        networks:
            - kafka-network
        environment:
            KAFKA_CFG_NODE_ID: 4
            KAFKA_CFG_PROCESS_ROLES: broker
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller_1:29092,2@kafka_controller_2:29093,3@kafka_controller_3:29094
            KAFKA_KRAFT_CLUSTER_ID: OGETnS3qyk2qgAXb0EcENQ
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9093
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_1:9092,EXTERNAL://localhost:9093
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            ALLOW_PLAINTEXT_LISTENER: yes
            KAFKA_ADVERTISED_HOST_NAME: kafka_broker_1
            KAFKA_BROKER_ID: 4
    kafka_broker_2:
        image: bitnami/kafka:3.4
        container_name: kafka_broker_2
        ports:
            - 9094:9094
            - 9095:9095
        networks:
            - kafka-network
        environment:
            KAFKA_CFG_NODE_ID: 5
            KAFKA_CFG_PROCESS_ROLES: broker
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller_1:29092,2@kafka_controller_2:29093,3@kafka_controller_3:29094
            KAFKA_KRAFT_CLUSTER_ID: OGETnS3qyk2qgAXb0EcENQ
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9094,EXTERNAL://:9095
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_2:9094,EXTERNAL://localhost:9095
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            ALLOW_PLAINTEXT_LISTENER: yes
            KAFKA_ADVERTISED_HOST_NAME: kafka_broker_2
            KAFKA_BROKER_ID: 5
    kafka_broker_3:
        image: bitnami/kafka:3.4
        container_name: kafka_broker_3
        ports:
            - 9096:9096
            - 9097:9097
        networks:
            - kafka-network
        environment:
            KAFKA_CFG_NODE_ID: 6
            KAFKA_CFG_PROCESS_ROLES: broker
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka_controller_1:29092,2@kafka_controller_2:29093,3@kafka_controller_3:29094
            KAFKA_KRAFT_CLUSTER_ID: OGETnS3qyk2qgAXb0EcENQ
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9096,EXTERNAL://:9097
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker_3:9096,EXTERNAL://localhost:9097
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            ALLOW_PLAINTEXT_LISTENER: yes
            KAFKA_ADVERTISED_HOST_NAME: kafka_broker_3
            KAFKA_BROKER_ID: 6

networks:
    kafka-network:
        driver: bridge